### ISSUE TITLE
how did you import keybindings from a different file? 

### ISSUE THREAD

**Issue by aurkaxi** [Ruturajn/Dotfiles#6]
sorry for creating an issue.
i see you've a separate file for keybindings and imported them by `from keybindins import *`
i made a file like this:
```
import os
import qtile bla bla bla
import bla bla bla
keys = [
bla bla bla
]
```
then went back to config.py added the line `from keybindings import *`

but qtile doesn't restart. if i remove this line it restarts. no error found from `$python -m py_compile config.py`

**Comment by Ruturajn** [comment]
Hi,
The line in my `config.py` is
```
from Keybindings import *
```
This is because, I have named the file `Keybindings.py`, with a capital `K`. So, maybe you are missing that, or another issue might be that python does not find that file, try placing it at the same level as your `config.py`. I hope this helps.

Thanks

EDIT: If you are planning to place the `Keybindings.py` file somewhere else, you can add it to the path, [like this](https://gitlab.com/ruturajn/RnOS_Welcome_App/-/blob/main/data/welcome-app/key_binds/display_keys.py#L8-L12) (this is what I have done, there are many ways to do this), so python can find it.

**Comment by aurkaxi** [comment]
ah yes, everything is good now. i will separate every section now haha. thank you sir. have a great day.

**Comment by Ruturajn** [comment]
You're welcome! Good Day
